[2023-07-27T09:16:24.553+0300] {processor.py:156} INFO - Started process (PID=26) to work on /opt/airflow/dags/google_trends_dag.py
[2023-07-27T09:16:24.554+0300] {processor.py:799} INFO - Processing file /opt/airflow/dags/google_trends_dag.py for tasks to queue
[2023-07-27T09:16:24.555+0300] {logging_mixin.py:149} INFO - [2023-07-27T09:16:24.555+0300] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/google_trends_dag.py
[2023-07-27T09:16:24.573+0300] {logging_mixin.py:149} INFO - [2023-07-27T09:16:24.572+0300] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/google_trends_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/google_trends_dag.py", line 6, in <module>
    from objects.socgen.sod_summery import SodSummery
ModuleNotFoundError: No module named 'objects.socgen'
[2023-07-27T09:16:24.574+0300] {processor.py:811} WARNING - No viable dags retrieved from /opt/airflow/dags/google_trends_dag.py
[2023-07-27T09:16:24.608+0300] {processor.py:178} INFO - Processing /opt/airflow/dags/google_trends_dag.py took 0.058 seconds
[2023-07-27T09:16:54.733+0300] {processor.py:156} INFO - Started process (PID=34) to work on /opt/airflow/dags/google_trends_dag.py
[2023-07-27T09:16:54.735+0300] {processor.py:799} INFO - Processing file /opt/airflow/dags/google_trends_dag.py for tasks to queue
[2023-07-27T09:16:54.735+0300] {logging_mixin.py:149} INFO - [2023-07-27T09:16:54.735+0300] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/google_trends_dag.py
[2023-07-27T09:16:54.745+0300] {logging_mixin.py:149} INFO - [2023-07-27T09:16:54.744+0300] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/google_trends_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/google_trends_dag.py", line 6, in <module>
    from objects.socgen.sod_summery import SodSummery
ModuleNotFoundError: No module named 'objects.socgen'
[2023-07-27T09:16:54.745+0300] {processor.py:811} WARNING - No viable dags retrieved from /opt/airflow/dags/google_trends_dag.py
[2023-07-27T09:16:54.769+0300] {processor.py:178} INFO - Processing /opt/airflow/dags/google_trends_dag.py took 0.040 seconds
[2023-07-27T09:16:59.773+0300] {processor.py:156} INFO - Started process (PID=35) to work on /opt/airflow/dags/google_trends_dag.py
[2023-07-27T09:16:59.774+0300] {processor.py:799} INFO - Processing file /opt/airflow/dags/google_trends_dag.py for tasks to queue
[2023-07-27T09:16:59.775+0300] {logging_mixin.py:149} INFO - [2023-07-27T09:16:59.775+0300] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/google_trends_dag.py
[2023-07-27T09:16:59.792+0300] {logging_mixin.py:149} INFO - [2023-07-27T09:16:59.791+0300] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/google_trends_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/google_trends_dag.py", line 9, in <module>
    from utils.utils import update_status
ModuleNotFoundError: No module named 'utils.utils'
[2023-07-27T09:16:59.793+0300] {processor.py:811} WARNING - No viable dags retrieved from /opt/airflow/dags/google_trends_dag.py
[2023-07-27T09:16:59.814+0300] {processor.py:178} INFO - Processing /opt/airflow/dags/google_trends_dag.py took 0.044 seconds
[2023-07-27T09:17:14.882+0300] {processor.py:156} INFO - Started process (PID=36) to work on /opt/airflow/dags/google_trends_dag.py
[2023-07-27T09:17:14.884+0300] {processor.py:799} INFO - Processing file /opt/airflow/dags/google_trends_dag.py for tasks to queue
[2023-07-27T09:17:14.885+0300] {logging_mixin.py:149} INFO - [2023-07-27T09:17:14.884+0300] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/google_trends_dag.py
[2023-07-27T09:17:14.906+0300] {logging_mixin.py:149} INFO - [2023-07-27T09:17:14.903+0300] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/google_trends_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/google_trends_dag.py", line 74, in <module>
    dag_creator = GooogleTrendsMonthly()
  File "/opt/airflow/dags/google_trends_dag.py", line 41, in __init__
    self.dag:DAG = self.create_dag()
  File "/opt/airflow/dags/google_trends_dag.py", line 54, in create_dag
    update_monthly: PythonOperator = PythonOperator(
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/baseoperator.py", line 429, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/python.py", line 168, in __init__
    raise AirflowException("`python_callable` param must be callable")
airflow.exceptions.AirflowException: `python_callable` param must be callable
[2023-07-27T09:17:14.906+0300] {processor.py:811} WARNING - No viable dags retrieved from /opt/airflow/dags/google_trends_dag.py
[2023-07-27T09:17:14.933+0300] {processor.py:178} INFO - Processing /opt/airflow/dags/google_trends_dag.py took 0.055 seconds
[2023-07-27T09:17:45.071+0300] {processor.py:156} INFO - Started process (PID=45) to work on /opt/airflow/dags/google_trends_dag.py
[2023-07-27T09:17:45.072+0300] {processor.py:799} INFO - Processing file /opt/airflow/dags/google_trends_dag.py for tasks to queue
[2023-07-27T09:17:45.073+0300] {logging_mixin.py:149} INFO - [2023-07-27T09:17:45.073+0300] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/google_trends_dag.py
[2023-07-27T09:17:45.089+0300] {logging_mixin.py:149} INFO - [2023-07-27T09:17:45.087+0300] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/google_trends_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/google_trends_dag.py", line 74, in <module>
    dag_creator = GooogleTrendsMonthly()
  File "/opt/airflow/dags/google_trends_dag.py", line 41, in __init__
    self.dag:DAG = self.create_dag()
  File "/opt/airflow/dags/google_trends_dag.py", line 54, in create_dag
    update_monthly: PythonOperator = PythonOperator(
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/baseoperator.py", line 429, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/python.py", line 168, in __init__
    raise AirflowException("`python_callable` param must be callable")
airflow.exceptions.AirflowException: `python_callable` param must be callable
[2023-07-27T09:17:45.089+0300] {processor.py:811} WARNING - No viable dags retrieved from /opt/airflow/dags/google_trends_dag.py
[2023-07-27T09:17:45.113+0300] {processor.py:178} INFO - Processing /opt/airflow/dags/google_trends_dag.py took 0.046 seconds
[2023-07-27T09:18:15.247+0300] {processor.py:156} INFO - Started process (PID=53) to work on /opt/airflow/dags/google_trends_dag.py
[2023-07-27T09:18:15.249+0300] {processor.py:799} INFO - Processing file /opt/airflow/dags/google_trends_dag.py for tasks to queue
[2023-07-27T09:18:15.249+0300] {logging_mixin.py:149} INFO - [2023-07-27T09:18:15.249+0300] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/google_trends_dag.py
[2023-07-27T09:18:15.272+0300] {logging_mixin.py:149} INFO - [2023-07-27T09:18:15.270+0300] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/google_trends_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/google_trends_dag.py", line 74, in <module>
    dag_creator = GooogleTrendsMonthly()
  File "/opt/airflow/dags/google_trends_dag.py", line 41, in __init__
    self.dag:DAG = self.create_dag()
  File "/opt/airflow/dags/google_trends_dag.py", line 54, in create_dag
    update_monthly: PythonOperator = PythonOperator(
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/baseoperator.py", line 429, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/python.py", line 168, in __init__
    raise AirflowException("`python_callable` param must be callable")
airflow.exceptions.AirflowException: `python_callable` param must be callable
[2023-07-27T09:18:15.273+0300] {processor.py:811} WARNING - No viable dags retrieved from /opt/airflow/dags/google_trends_dag.py
[2023-07-27T09:18:15.300+0300] {processor.py:178} INFO - Processing /opt/airflow/dags/google_trends_dag.py took 0.059 seconds
[2023-07-27T09:18:45.427+0300] {processor.py:156} INFO - Started process (PID=61) to work on /opt/airflow/dags/google_trends_dag.py
[2023-07-27T09:18:45.428+0300] {processor.py:799} INFO - Processing file /opt/airflow/dags/google_trends_dag.py for tasks to queue
[2023-07-27T09:18:45.428+0300] {logging_mixin.py:149} INFO - [2023-07-27T09:18:45.428+0300] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/google_trends_dag.py
[2023-07-27T09:18:45.443+0300] {logging_mixin.py:149} INFO - [2023-07-27T09:18:45.441+0300] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/google_trends_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/google_trends_dag.py", line 74, in <module>
    dag_creator = GooogleTrendsMonthly()
  File "/opt/airflow/dags/google_trends_dag.py", line 41, in __init__
    self.dag:DAG = self.create_dag()
  File "/opt/airflow/dags/google_trends_dag.py", line 54, in create_dag
    update_monthly: PythonOperator = PythonOperator(
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/baseoperator.py", line 429, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/python.py", line 168, in __init__
    raise AirflowException("`python_callable` param must be callable")
airflow.exceptions.AirflowException: `python_callable` param must be callable
[2023-07-27T09:18:45.443+0300] {processor.py:811} WARNING - No viable dags retrieved from /opt/airflow/dags/google_trends_dag.py
[2023-07-27T09:18:45.462+0300] {processor.py:178} INFO - Processing /opt/airflow/dags/google_trends_dag.py took 0.039 seconds
[2023-07-27T09:19:15.584+0300] {processor.py:156} INFO - Started process (PID=69) to work on /opt/airflow/dags/google_trends_dag.py
[2023-07-27T09:19:15.585+0300] {processor.py:799} INFO - Processing file /opt/airflow/dags/google_trends_dag.py for tasks to queue
[2023-07-27T09:19:15.586+0300] {logging_mixin.py:149} INFO - [2023-07-27T09:19:15.586+0300] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/google_trends_dag.py
[2023-07-27T09:19:15.600+0300] {logging_mixin.py:149} INFO - [2023-07-27T09:19:15.598+0300] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/google_trends_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/google_trends_dag.py", line 74, in <module>
    dag_creator = GooogleTrendsMonthly()
  File "/opt/airflow/dags/google_trends_dag.py", line 41, in __init__
    self.dag:DAG = self.create_dag()
  File "/opt/airflow/dags/google_trends_dag.py", line 54, in create_dag
    update_monthly: PythonOperator = PythonOperator(
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/baseoperator.py", line 429, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/python.py", line 168, in __init__
    raise AirflowException("`python_callable` param must be callable")
airflow.exceptions.AirflowException: `python_callable` param must be callable
[2023-07-27T09:19:15.600+0300] {processor.py:811} WARNING - No viable dags retrieved from /opt/airflow/dags/google_trends_dag.py
[2023-07-27T09:19:15.622+0300] {processor.py:178} INFO - Processing /opt/airflow/dags/google_trends_dag.py took 0.042 seconds
[2023-07-27T09:19:45.740+0300] {processor.py:156} INFO - Started process (PID=77) to work on /opt/airflow/dags/google_trends_dag.py
[2023-07-27T09:19:45.742+0300] {processor.py:799} INFO - Processing file /opt/airflow/dags/google_trends_dag.py for tasks to queue
[2023-07-27T09:19:45.744+0300] {logging_mixin.py:149} INFO - [2023-07-27T09:19:45.743+0300] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/google_trends_dag.py
[2023-07-27T09:19:45.759+0300] {logging_mixin.py:149} INFO - [2023-07-27T09:19:45.757+0300] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/google_trends_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/google_trends_dag.py", line 74, in <module>
    dag_creator = GooogleTrendsMonthly()
  File "/opt/airflow/dags/google_trends_dag.py", line 41, in __init__
    self.dag:DAG = self.create_dag()
  File "/opt/airflow/dags/google_trends_dag.py", line 54, in create_dag
    update_monthly: PythonOperator = PythonOperator(
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/baseoperator.py", line 429, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/python.py", line 168, in __init__
    raise AirflowException("`python_callable` param must be callable")
airflow.exceptions.AirflowException: `python_callable` param must be callable
[2023-07-27T09:19:45.759+0300] {processor.py:811} WARNING - No viable dags retrieved from /opt/airflow/dags/google_trends_dag.py
[2023-07-27T09:19:45.779+0300] {processor.py:178} INFO - Processing /opt/airflow/dags/google_trends_dag.py took 0.043 seconds
[2023-07-27T09:20:15.922+0300] {processor.py:156} INFO - Started process (PID=85) to work on /opt/airflow/dags/google_trends_dag.py
[2023-07-27T09:20:15.922+0300] {processor.py:799} INFO - Processing file /opt/airflow/dags/google_trends_dag.py for tasks to queue
[2023-07-27T09:20:15.923+0300] {logging_mixin.py:149} INFO - [2023-07-27T09:20:15.923+0300] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/google_trends_dag.py
[2023-07-27T09:20:15.934+0300] {logging_mixin.py:149} INFO - [2023-07-27T09:20:15.933+0300] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/google_trends_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/google_trends_dag.py", line 74, in <module>
    dag_creator = GooogleTrendsMonthly()
  File "/opt/airflow/dags/google_trends_dag.py", line 41, in __init__
    self.dag:DAG = self.create_dag()
  File "/opt/airflow/dags/google_trends_dag.py", line 54, in create_dag
    update_monthly: PythonOperator = PythonOperator(
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/baseoperator.py", line 429, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/python.py", line 168, in __init__
    raise AirflowException("`python_callable` param must be callable")
airflow.exceptions.AirflowException: `python_callable` param must be callable
[2023-07-27T09:20:15.935+0300] {processor.py:811} WARNING - No viable dags retrieved from /opt/airflow/dags/google_trends_dag.py
[2023-07-27T09:20:15.953+0300] {processor.py:178} INFO - Processing /opt/airflow/dags/google_trends_dag.py took 0.034 seconds
[2023-07-27T09:20:46.079+0300] {processor.py:156} INFO - Started process (PID=92) to work on /opt/airflow/dags/google_trends_dag.py
[2023-07-27T09:20:46.080+0300] {processor.py:799} INFO - Processing file /opt/airflow/dags/google_trends_dag.py for tasks to queue
[2023-07-27T09:20:46.081+0300] {logging_mixin.py:149} INFO - [2023-07-27T09:20:46.081+0300] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/google_trends_dag.py
[2023-07-27T09:20:46.093+0300] {logging_mixin.py:149} INFO - [2023-07-27T09:20:46.091+0300] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/google_trends_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/google_trends_dag.py", line 74, in <module>
    dag_creator = GooogleTrendsMonthly()
  File "/opt/airflow/dags/google_trends_dag.py", line 41, in __init__
    self.dag:DAG = self.create_dag()
  File "/opt/airflow/dags/google_trends_dag.py", line 54, in create_dag
    update_monthly: PythonOperator = PythonOperator(
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/baseoperator.py", line 429, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/python.py", line 168, in __init__
    raise AirflowException("`python_callable` param must be callable")
airflow.exceptions.AirflowException: `python_callable` param must be callable
[2023-07-27T09:20:46.093+0300] {processor.py:811} WARNING - No viable dags retrieved from /opt/airflow/dags/google_trends_dag.py
[2023-07-27T09:20:46.111+0300] {processor.py:178} INFO - Processing /opt/airflow/dags/google_trends_dag.py took 0.035 seconds
[2023-07-27T09:21:16.244+0300] {processor.py:156} INFO - Started process (PID=100) to work on /opt/airflow/dags/google_trends_dag.py
[2023-07-27T09:21:16.246+0300] {processor.py:799} INFO - Processing file /opt/airflow/dags/google_trends_dag.py for tasks to queue
[2023-07-27T09:21:16.247+0300] {logging_mixin.py:149} INFO - [2023-07-27T09:21:16.246+0300] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/google_trends_dag.py
[2023-07-27T09:21:16.264+0300] {logging_mixin.py:149} INFO - [2023-07-27T09:21:16.262+0300] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/google_trends_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/google_trends_dag.py", line 74, in <module>
    dag_creator = GooogleTrendsMonthly()
  File "/opt/airflow/dags/google_trends_dag.py", line 41, in __init__
    self.dag:DAG = self.create_dag()
  File "/opt/airflow/dags/google_trends_dag.py", line 54, in create_dag
    update_monthly: PythonOperator = PythonOperator(
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/baseoperator.py", line 429, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/python.py", line 168, in __init__
    raise AirflowException("`python_callable` param must be callable")
airflow.exceptions.AirflowException: `python_callable` param must be callable
[2023-07-27T09:21:16.265+0300] {processor.py:811} WARNING - No viable dags retrieved from /opt/airflow/dags/google_trends_dag.py
[2023-07-27T09:21:16.288+0300] {processor.py:178} INFO - Processing /opt/airflow/dags/google_trends_dag.py took 0.049 seconds
[2023-07-27T09:21:46.417+0300] {processor.py:156} INFO - Started process (PID=108) to work on /opt/airflow/dags/google_trends_dag.py
[2023-07-27T09:21:46.418+0300] {processor.py:799} INFO - Processing file /opt/airflow/dags/google_trends_dag.py for tasks to queue
[2023-07-27T09:21:46.419+0300] {logging_mixin.py:149} INFO - [2023-07-27T09:21:46.418+0300] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/google_trends_dag.py
[2023-07-27T09:21:46.435+0300] {logging_mixin.py:149} INFO - [2023-07-27T09:21:46.434+0300] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/google_trends_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/google_trends_dag.py", line 74, in <module>
    dag_creator = GooogleTrendsMonthly()
  File "/opt/airflow/dags/google_trends_dag.py", line 41, in __init__
    self.dag:DAG = self.create_dag()
  File "/opt/airflow/dags/google_trends_dag.py", line 54, in create_dag
    update_monthly: PythonOperator = PythonOperator(
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/baseoperator.py", line 429, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/python.py", line 168, in __init__
    raise AirflowException("`python_callable` param must be callable")
airflow.exceptions.AirflowException: `python_callable` param must be callable
[2023-07-27T09:21:46.436+0300] {processor.py:811} WARNING - No viable dags retrieved from /opt/airflow/dags/google_trends_dag.py
[2023-07-27T09:21:46.461+0300] {processor.py:178} INFO - Processing /opt/airflow/dags/google_trends_dag.py took 0.048 seconds
[2023-07-27T09:22:16.569+0300] {processor.py:156} INFO - Started process (PID=115) to work on /opt/airflow/dags/google_trends_dag.py
[2023-07-27T09:22:16.571+0300] {processor.py:799} INFO - Processing file /opt/airflow/dags/google_trends_dag.py for tasks to queue
[2023-07-27T09:22:16.572+0300] {logging_mixin.py:149} INFO - [2023-07-27T09:22:16.571+0300] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/google_trends_dag.py
[2023-07-27T09:22:16.588+0300] {logging_mixin.py:149} INFO - [2023-07-27T09:22:16.586+0300] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/google_trends_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/google_trends_dag.py", line 74, in <module>
    dag_creator = GooogleTrendsMonthly()
  File "/opt/airflow/dags/google_trends_dag.py", line 41, in __init__
    self.dag:DAG = self.create_dag()
  File "/opt/airflow/dags/google_trends_dag.py", line 54, in create_dag
    update_monthly: PythonOperator = PythonOperator(
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/baseoperator.py", line 429, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/python.py", line 168, in __init__
    raise AirflowException("`python_callable` param must be callable")
airflow.exceptions.AirflowException: `python_callable` param must be callable
[2023-07-27T09:22:16.589+0300] {processor.py:811} WARNING - No viable dags retrieved from /opt/airflow/dags/google_trends_dag.py
[2023-07-27T09:22:16.610+0300] {processor.py:178} INFO - Processing /opt/airflow/dags/google_trends_dag.py took 0.044 seconds
[2023-07-27T09:22:46.747+0300] {processor.py:156} INFO - Started process (PID=123) to work on /opt/airflow/dags/google_trends_dag.py
[2023-07-27T09:22:46.748+0300] {processor.py:799} INFO - Processing file /opt/airflow/dags/google_trends_dag.py for tasks to queue
[2023-07-27T09:22:46.749+0300] {logging_mixin.py:149} INFO - [2023-07-27T09:22:46.749+0300] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/google_trends_dag.py
[2023-07-27T09:22:46.764+0300] {logging_mixin.py:149} INFO - [2023-07-27T09:22:46.762+0300] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/google_trends_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/google_trends_dag.py", line 74, in <module>
    dag_creator = GooogleTrendsMonthly()
  File "/opt/airflow/dags/google_trends_dag.py", line 41, in __init__
    self.dag:DAG = self.create_dag()
  File "/opt/airflow/dags/google_trends_dag.py", line 54, in create_dag
    update_monthly: PythonOperator = PythonOperator(
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/baseoperator.py", line 429, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/python.py", line 168, in __init__
    raise AirflowException("`python_callable` param must be callable")
airflow.exceptions.AirflowException: `python_callable` param must be callable
[2023-07-27T09:22:46.764+0300] {processor.py:811} WARNING - No viable dags retrieved from /opt/airflow/dags/google_trends_dag.py
[2023-07-27T09:22:46.784+0300] {processor.py:178} INFO - Processing /opt/airflow/dags/google_trends_dag.py took 0.041 seconds
[2023-07-27T09:23:16.907+0300] {processor.py:156} INFO - Started process (PID=131) to work on /opt/airflow/dags/google_trends_dag.py
[2023-07-27T09:23:16.909+0300] {processor.py:799} INFO - Processing file /opt/airflow/dags/google_trends_dag.py for tasks to queue
[2023-07-27T09:23:16.910+0300] {logging_mixin.py:149} INFO - [2023-07-27T09:23:16.909+0300] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/google_trends_dag.py
[2023-07-27T09:23:16.934+0300] {logging_mixin.py:149} INFO - [2023-07-27T09:23:16.932+0300] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/google_trends_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/google_trends_dag.py", line 74, in <module>
    dag_creator = GooogleTrendsMonthly()
  File "/opt/airflow/dags/google_trends_dag.py", line 41, in __init__
    self.dag:DAG = self.create_dag()
  File "/opt/airflow/dags/google_trends_dag.py", line 54, in create_dag
    update_monthly: PythonOperator = PythonOperator(
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/baseoperator.py", line 429, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/python.py", line 168, in __init__
    raise AirflowException("`python_callable` param must be callable")
airflow.exceptions.AirflowException: `python_callable` param must be callable
[2023-07-27T09:23:16.935+0300] {processor.py:811} WARNING - No viable dags retrieved from /opt/airflow/dags/google_trends_dag.py
[2023-07-27T09:23:16.965+0300] {processor.py:178} INFO - Processing /opt/airflow/dags/google_trends_dag.py took 0.061 seconds
[2023-07-27T09:23:47.067+0300] {processor.py:156} INFO - Started process (PID=140) to work on /opt/airflow/dags/google_trends_dag.py
[2023-07-27T09:23:47.068+0300] {processor.py:799} INFO - Processing file /opt/airflow/dags/google_trends_dag.py for tasks to queue
[2023-07-27T09:23:47.069+0300] {logging_mixin.py:149} INFO - [2023-07-27T09:23:47.068+0300] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/google_trends_dag.py
[2023-07-27T09:23:47.086+0300] {logging_mixin.py:149} INFO - [2023-07-27T09:23:47.084+0300] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/google_trends_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/google_trends_dag.py", line 74, in <module>
    dag_creator = GooogleTrendsMonthly()
  File "/opt/airflow/dags/google_trends_dag.py", line 41, in __init__
    self.dag:DAG = self.create_dag()
  File "/opt/airflow/dags/google_trends_dag.py", line 54, in create_dag
    update_monthly: PythonOperator = PythonOperator(
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/baseoperator.py", line 429, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/python.py", line 168, in __init__
    raise AirflowException("`python_callable` param must be callable")
airflow.exceptions.AirflowException: `python_callable` param must be callable
[2023-07-27T09:23:47.087+0300] {processor.py:811} WARNING - No viable dags retrieved from /opt/airflow/dags/google_trends_dag.py
[2023-07-27T09:23:47.113+0300] {processor.py:178} INFO - Processing /opt/airflow/dags/google_trends_dag.py took 0.050 seconds
[2023-07-27T09:24:17.264+0300] {processor.py:156} INFO - Started process (PID=148) to work on /opt/airflow/dags/google_trends_dag.py
[2023-07-27T09:24:17.265+0300] {processor.py:799} INFO - Processing file /opt/airflow/dags/google_trends_dag.py for tasks to queue
[2023-07-27T09:24:17.266+0300] {logging_mixin.py:149} INFO - [2023-07-27T09:24:17.266+0300] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/google_trends_dag.py
[2023-07-27T09:24:17.287+0300] {logging_mixin.py:149} INFO - [2023-07-27T09:24:17.284+0300] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/google_trends_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/google_trends_dag.py", line 74, in <module>
    dag_creator = GooogleTrendsMonthly()
  File "/opt/airflow/dags/google_trends_dag.py", line 41, in __init__
    self.dag:DAG = self.create_dag()
  File "/opt/airflow/dags/google_trends_dag.py", line 54, in create_dag
    update_monthly: PythonOperator = PythonOperator(
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/baseoperator.py", line 429, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/python.py", line 168, in __init__
    raise AirflowException("`python_callable` param must be callable")
airflow.exceptions.AirflowException: `python_callable` param must be callable
[2023-07-27T09:24:17.288+0300] {processor.py:811} WARNING - No viable dags retrieved from /opt/airflow/dags/google_trends_dag.py
[2023-07-27T09:24:17.317+0300] {processor.py:178} INFO - Processing /opt/airflow/dags/google_trends_dag.py took 0.056 seconds
[2023-07-27T09:24:47.425+0300] {processor.py:156} INFO - Started process (PID=156) to work on /opt/airflow/dags/google_trends_dag.py
[2023-07-27T09:24:47.426+0300] {processor.py:799} INFO - Processing file /opt/airflow/dags/google_trends_dag.py for tasks to queue
[2023-07-27T09:24:47.427+0300] {logging_mixin.py:149} INFO - [2023-07-27T09:24:47.426+0300] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/google_trends_dag.py
[2023-07-27T09:24:47.440+0300] {logging_mixin.py:149} INFO - [2023-07-27T09:24:47.438+0300] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/google_trends_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/google_trends_dag.py", line 74, in <module>
    dag_creator = GooogleTrendsMonthly()
  File "/opt/airflow/dags/google_trends_dag.py", line 41, in __init__
    self.dag:DAG = self.create_dag()
  File "/opt/airflow/dags/google_trends_dag.py", line 54, in create_dag
    update_monthly: PythonOperator = PythonOperator(
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/baseoperator.py", line 429, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/python.py", line 168, in __init__
    raise AirflowException("`python_callable` param must be callable")
airflow.exceptions.AirflowException: `python_callable` param must be callable
[2023-07-27T09:24:47.440+0300] {processor.py:811} WARNING - No viable dags retrieved from /opt/airflow/dags/google_trends_dag.py
[2023-07-27T09:24:47.463+0300] {processor.py:178} INFO - Processing /opt/airflow/dags/google_trends_dag.py took 0.042 seconds
[2023-07-27T09:25:17.610+0300] {processor.py:156} INFO - Started process (PID=164) to work on /opt/airflow/dags/google_trends_dag.py
[2023-07-27T09:25:17.611+0300] {processor.py:799} INFO - Processing file /opt/airflow/dags/google_trends_dag.py for tasks to queue
[2023-07-27T09:25:17.611+0300] {logging_mixin.py:149} INFO - [2023-07-27T09:25:17.611+0300] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/google_trends_dag.py
[2023-07-27T09:25:17.624+0300] {logging_mixin.py:149} INFO - [2023-07-27T09:25:17.623+0300] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/google_trends_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/google_trends_dag.py", line 74, in <module>
    dag_creator = GooogleTrendsMonthly()
  File "/opt/airflow/dags/google_trends_dag.py", line 41, in __init__
    self.dag:DAG = self.create_dag()
  File "/opt/airflow/dags/google_trends_dag.py", line 54, in create_dag
    update_monthly: PythonOperator = PythonOperator(
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/baseoperator.py", line 429, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/python.py", line 168, in __init__
    raise AirflowException("`python_callable` param must be callable")
airflow.exceptions.AirflowException: `python_callable` param must be callable
[2023-07-27T09:25:17.624+0300] {processor.py:811} WARNING - No viable dags retrieved from /opt/airflow/dags/google_trends_dag.py
[2023-07-27T09:25:17.642+0300] {processor.py:178} INFO - Processing /opt/airflow/dags/google_trends_dag.py took 0.035 seconds
[2023-07-27T09:25:47.779+0300] {processor.py:156} INFO - Started process (PID=172) to work on /opt/airflow/dags/google_trends_dag.py
[2023-07-27T09:25:47.781+0300] {processor.py:799} INFO - Processing file /opt/airflow/dags/google_trends_dag.py for tasks to queue
[2023-07-27T09:25:47.782+0300] {logging_mixin.py:149} INFO - [2023-07-27T09:25:47.782+0300] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/google_trends_dag.py
[2023-07-27T09:25:47.801+0300] {logging_mixin.py:149} INFO - [2023-07-27T09:25:47.799+0300] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/google_trends_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/google_trends_dag.py", line 74, in <module>
    dag_creator = GooogleTrendsMonthly()
  File "/opt/airflow/dags/google_trends_dag.py", line 41, in __init__
    self.dag:DAG = self.create_dag()
  File "/opt/airflow/dags/google_trends_dag.py", line 54, in create_dag
    update_monthly: PythonOperator = PythonOperator(
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/baseoperator.py", line 429, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/python.py", line 168, in __init__
    raise AirflowException("`python_callable` param must be callable")
airflow.exceptions.AirflowException: `python_callable` param must be callable
[2023-07-27T09:25:47.801+0300] {processor.py:811} WARNING - No viable dags retrieved from /opt/airflow/dags/google_trends_dag.py
[2023-07-27T09:25:47.832+0300] {processor.py:178} INFO - Processing /opt/airflow/dags/google_trends_dag.py took 0.057 seconds
[2023-07-27T09:26:17.938+0300] {processor.py:156} INFO - Started process (PID=180) to work on /opt/airflow/dags/google_trends_dag.py
[2023-07-27T09:26:17.939+0300] {processor.py:799} INFO - Processing file /opt/airflow/dags/google_trends_dag.py for tasks to queue
[2023-07-27T09:26:17.940+0300] {logging_mixin.py:149} INFO - [2023-07-27T09:26:17.940+0300] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/google_trends_dag.py
[2023-07-27T09:26:17.954+0300] {logging_mixin.py:149} INFO - [2023-07-27T09:26:17.953+0300] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/google_trends_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/google_trends_dag.py", line 74, in <module>
    dag_creator = GooogleTrendsMonthly()
  File "/opt/airflow/dags/google_trends_dag.py", line 41, in __init__
    self.dag:DAG = self.create_dag()
  File "/opt/airflow/dags/google_trends_dag.py", line 54, in create_dag
    update_monthly: PythonOperator = PythonOperator(
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/baseoperator.py", line 429, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/python.py", line 168, in __init__
    raise AirflowException("`python_callable` param must be callable")
airflow.exceptions.AirflowException: `python_callable` param must be callable
[2023-07-27T09:26:17.955+0300] {processor.py:811} WARNING - No viable dags retrieved from /opt/airflow/dags/google_trends_dag.py
[2023-07-27T09:26:17.980+0300] {processor.py:178} INFO - Processing /opt/airflow/dags/google_trends_dag.py took 0.045 seconds
[2023-07-27T09:26:48.140+0300] {processor.py:156} INFO - Started process (PID=188) to work on /opt/airflow/dags/google_trends_dag.py
[2023-07-27T09:26:48.142+0300] {processor.py:799} INFO - Processing file /opt/airflow/dags/google_trends_dag.py for tasks to queue
[2023-07-27T09:26:48.142+0300] {logging_mixin.py:149} INFO - [2023-07-27T09:26:48.142+0300] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/google_trends_dag.py
[2023-07-27T09:26:48.156+0300] {logging_mixin.py:149} INFO - [2023-07-27T09:26:48.154+0300] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/google_trends_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/google_trends_dag.py", line 74, in <module>
    dag_creator = GooogleTrendsMonthly()
  File "/opt/airflow/dags/google_trends_dag.py", line 41, in __init__
    self.dag:DAG = self.create_dag()
  File "/opt/airflow/dags/google_trends_dag.py", line 54, in create_dag
    update_monthly: PythonOperator = PythonOperator(
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/baseoperator.py", line 429, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/python.py", line 168, in __init__
    raise AirflowException("`python_callable` param must be callable")
airflow.exceptions.AirflowException: `python_callable` param must be callable
[2023-07-27T09:26:48.156+0300] {processor.py:811} WARNING - No viable dags retrieved from /opt/airflow/dags/google_trends_dag.py
[2023-07-27T09:26:48.177+0300] {processor.py:178} INFO - Processing /opt/airflow/dags/google_trends_dag.py took 0.040 seconds
[2023-07-27T09:27:18.306+0300] {processor.py:156} INFO - Started process (PID=197) to work on /opt/airflow/dags/google_trends_dag.py
[2023-07-27T09:27:18.308+0300] {processor.py:799} INFO - Processing file /opt/airflow/dags/google_trends_dag.py for tasks to queue
[2023-07-27T09:27:18.308+0300] {logging_mixin.py:149} INFO - [2023-07-27T09:27:18.308+0300] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/google_trends_dag.py
[2023-07-27T09:27:18.329+0300] {logging_mixin.py:149} INFO - [2023-07-27T09:27:18.327+0300] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/google_trends_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/google_trends_dag.py", line 74, in <module>
    dag_creator = GooogleTrendsMonthly()
  File "/opt/airflow/dags/google_trends_dag.py", line 41, in __init__
    self.dag:DAG = self.create_dag()
  File "/opt/airflow/dags/google_trends_dag.py", line 54, in create_dag
    update_monthly: PythonOperator = PythonOperator(
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/baseoperator.py", line 429, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/python.py", line 168, in __init__
    raise AirflowException("`python_callable` param must be callable")
airflow.exceptions.AirflowException: `python_callable` param must be callable
[2023-07-27T09:27:18.329+0300] {processor.py:811} WARNING - No viable dags retrieved from /opt/airflow/dags/google_trends_dag.py
[2023-07-27T09:27:18.358+0300] {processor.py:178} INFO - Processing /opt/airflow/dags/google_trends_dag.py took 0.056 seconds
[2023-07-27T09:27:48.465+0300] {processor.py:156} INFO - Started process (PID=205) to work on /opt/airflow/dags/google_trends_dag.py
[2023-07-27T09:27:48.466+0300] {processor.py:799} INFO - Processing file /opt/airflow/dags/google_trends_dag.py for tasks to queue
[2023-07-27T09:27:48.467+0300] {logging_mixin.py:149} INFO - [2023-07-27T09:27:48.467+0300] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/google_trends_dag.py
[2023-07-27T09:27:48.488+0300] {logging_mixin.py:149} INFO - [2023-07-27T09:27:48.486+0300] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/google_trends_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/google_trends_dag.py", line 74, in <module>
    dag_creator = GooogleTrendsMonthly()
  File "/opt/airflow/dags/google_trends_dag.py", line 41, in __init__
    self.dag:DAG = self.create_dag()
  File "/opt/airflow/dags/google_trends_dag.py", line 54, in create_dag
    update_monthly: PythonOperator = PythonOperator(
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/baseoperator.py", line 429, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/python.py", line 168, in __init__
    raise AirflowException("`python_callable` param must be callable")
airflow.exceptions.AirflowException: `python_callable` param must be callable
[2023-07-27T09:27:48.489+0300] {processor.py:811} WARNING - No viable dags retrieved from /opt/airflow/dags/google_trends_dag.py
[2023-07-27T09:27:48.511+0300] {processor.py:178} INFO - Processing /opt/airflow/dags/google_trends_dag.py took 0.050 seconds
[2023-07-27T09:28:18.657+0300] {processor.py:156} INFO - Started process (PID=214) to work on /opt/airflow/dags/google_trends_dag.py
[2023-07-27T09:28:18.658+0300] {processor.py:799} INFO - Processing file /opt/airflow/dags/google_trends_dag.py for tasks to queue
[2023-07-27T09:28:18.659+0300] {logging_mixin.py:149} INFO - [2023-07-27T09:28:18.659+0300] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/google_trends_dag.py
[2023-07-27T09:28:18.676+0300] {logging_mixin.py:149} INFO - [2023-07-27T09:28:18.674+0300] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/google_trends_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/google_trends_dag.py", line 74, in <module>
    dag_creator = GooogleTrendsMonthly()
  File "/opt/airflow/dags/google_trends_dag.py", line 41, in __init__
    self.dag:DAG = self.create_dag()
  File "/opt/airflow/dags/google_trends_dag.py", line 54, in create_dag
    update_monthly: PythonOperator = PythonOperator(
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/baseoperator.py", line 429, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/python.py", line 168, in __init__
    raise AirflowException("`python_callable` param must be callable")
airflow.exceptions.AirflowException: `python_callable` param must be callable
[2023-07-27T09:28:18.677+0300] {processor.py:811} WARNING - No viable dags retrieved from /opt/airflow/dags/google_trends_dag.py
[2023-07-27T09:28:18.702+0300] {processor.py:178} INFO - Processing /opt/airflow/dags/google_trends_dag.py took 0.049 seconds
[2023-07-27T09:28:48.814+0300] {processor.py:156} INFO - Started process (PID=222) to work on /opt/airflow/dags/google_trends_dag.py
[2023-07-27T09:28:48.816+0300] {processor.py:799} INFO - Processing file /opt/airflow/dags/google_trends_dag.py for tasks to queue
[2023-07-27T09:28:48.817+0300] {logging_mixin.py:149} INFO - [2023-07-27T09:28:48.817+0300] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/google_trends_dag.py
[2023-07-27T09:28:48.841+0300] {logging_mixin.py:149} INFO - [2023-07-27T09:28:48.839+0300] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/google_trends_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/google_trends_dag.py", line 74, in <module>
    dag_creator = GooogleTrendsMonthly()
  File "/opt/airflow/dags/google_trends_dag.py", line 41, in __init__
    self.dag:DAG = self.create_dag()
  File "/opt/airflow/dags/google_trends_dag.py", line 54, in create_dag
    update_monthly: PythonOperator = PythonOperator(
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/baseoperator.py", line 429, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/python.py", line 168, in __init__
    raise AirflowException("`python_callable` param must be callable")
airflow.exceptions.AirflowException: `python_callable` param must be callable
[2023-07-27T09:28:48.842+0300] {processor.py:811} WARNING - No viable dags retrieved from /opt/airflow/dags/google_trends_dag.py
[2023-07-27T09:28:48.869+0300] {processor.py:178} INFO - Processing /opt/airflow/dags/google_trends_dag.py took 0.060 seconds
[2023-07-27T09:29:19.004+0300] {processor.py:156} INFO - Started process (PID=230) to work on /opt/airflow/dags/google_trends_dag.py
[2023-07-27T09:29:19.005+0300] {processor.py:799} INFO - Processing file /opt/airflow/dags/google_trends_dag.py for tasks to queue
[2023-07-27T09:29:19.006+0300] {logging_mixin.py:149} INFO - [2023-07-27T09:29:19.006+0300] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/google_trends_dag.py
[2023-07-27T09:29:19.025+0300] {logging_mixin.py:149} INFO - [2023-07-27T09:29:19.023+0300] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/google_trends_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/google_trends_dag.py", line 74, in <module>
    dag_creator = GooogleTrendsMonthly()
  File "/opt/airflow/dags/google_trends_dag.py", line 41, in __init__
    self.dag:DAG = self.create_dag()
  File "/opt/airflow/dags/google_trends_dag.py", line 54, in create_dag
    update_monthly: PythonOperator = PythonOperator(
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/baseoperator.py", line 429, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/python.py", line 168, in __init__
    raise AirflowException("`python_callable` param must be callable")
airflow.exceptions.AirflowException: `python_callable` param must be callable
[2023-07-27T09:29:19.026+0300] {processor.py:811} WARNING - No viable dags retrieved from /opt/airflow/dags/google_trends_dag.py
[2023-07-27T09:29:19.046+0300] {processor.py:178} INFO - Processing /opt/airflow/dags/google_trends_dag.py took 0.046 seconds
[2023-07-27T09:29:49.158+0300] {processor.py:156} INFO - Started process (PID=238) to work on /opt/airflow/dags/google_trends_dag.py
[2023-07-27T09:29:49.160+0300] {processor.py:799} INFO - Processing file /opt/airflow/dags/google_trends_dag.py for tasks to queue
[2023-07-27T09:29:49.161+0300] {logging_mixin.py:149} INFO - [2023-07-27T09:29:49.160+0300] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/google_trends_dag.py
[2023-07-27T09:29:49.179+0300] {logging_mixin.py:149} INFO - [2023-07-27T09:29:49.177+0300] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/google_trends_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/google_trends_dag.py", line 74, in <module>
    dag_creator = GooogleTrendsMonthly()
  File "/opt/airflow/dags/google_trends_dag.py", line 41, in __init__
    self.dag:DAG = self.create_dag()
  File "/opt/airflow/dags/google_trends_dag.py", line 54, in create_dag
    update_monthly: PythonOperator = PythonOperator(
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/baseoperator.py", line 429, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/python.py", line 168, in __init__
    raise AirflowException("`python_callable` param must be callable")
airflow.exceptions.AirflowException: `python_callable` param must be callable
[2023-07-27T09:29:49.179+0300] {processor.py:811} WARNING - No viable dags retrieved from /opt/airflow/dags/google_trends_dag.py
[2023-07-27T09:29:49.201+0300] {processor.py:178} INFO - Processing /opt/airflow/dags/google_trends_dag.py took 0.047 seconds
[2023-07-27T09:30:19.319+0300] {processor.py:156} INFO - Started process (PID=246) to work on /opt/airflow/dags/google_trends_dag.py
[2023-07-27T09:30:19.321+0300] {processor.py:799} INFO - Processing file /opt/airflow/dags/google_trends_dag.py for tasks to queue
[2023-07-27T09:30:19.322+0300] {logging_mixin.py:149} INFO - [2023-07-27T09:30:19.322+0300] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/google_trends_dag.py
[2023-07-27T09:30:19.344+0300] {logging_mixin.py:149} INFO - [2023-07-27T09:30:19.341+0300] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/google_trends_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/google_trends_dag.py", line 74, in <module>
    dag_creator = GooogleTrendsMonthly()
  File "/opt/airflow/dags/google_trends_dag.py", line 41, in __init__
    self.dag:DAG = self.create_dag()
  File "/opt/airflow/dags/google_trends_dag.py", line 54, in create_dag
    update_monthly: PythonOperator = PythonOperator(
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/baseoperator.py", line 429, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/python.py", line 168, in __init__
    raise AirflowException("`python_callable` param must be callable")
airflow.exceptions.AirflowException: `python_callable` param must be callable
[2023-07-27T09:30:19.344+0300] {processor.py:811} WARNING - No viable dags retrieved from /opt/airflow/dags/google_trends_dag.py
[2023-07-27T09:30:19.366+0300] {processor.py:178} INFO - Processing /opt/airflow/dags/google_trends_dag.py took 0.052 seconds
[2023-07-27T09:30:49.497+0300] {processor.py:156} INFO - Started process (PID=254) to work on /opt/airflow/dags/google_trends_dag.py
[2023-07-27T09:30:49.498+0300] {processor.py:799} INFO - Processing file /opt/airflow/dags/google_trends_dag.py for tasks to queue
[2023-07-27T09:30:49.499+0300] {logging_mixin.py:149} INFO - [2023-07-27T09:30:49.499+0300] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/google_trends_dag.py
[2023-07-27T09:30:49.513+0300] {logging_mixin.py:149} INFO - [2023-07-27T09:30:49.511+0300] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/google_trends_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/google_trends_dag.py", line 74, in <module>
    dag_creator = GooogleTrendsMonthly()
  File "/opt/airflow/dags/google_trends_dag.py", line 41, in __init__
    self.dag:DAG = self.create_dag()
  File "/opt/airflow/dags/google_trends_dag.py", line 54, in create_dag
    update_monthly: PythonOperator = PythonOperator(
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/baseoperator.py", line 429, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/python.py", line 168, in __init__
    raise AirflowException("`python_callable` param must be callable")
airflow.exceptions.AirflowException: `python_callable` param must be callable
[2023-07-27T09:30:49.514+0300] {processor.py:811} WARNING - No viable dags retrieved from /opt/airflow/dags/google_trends_dag.py
[2023-07-27T09:30:49.542+0300] {processor.py:178} INFO - Processing /opt/airflow/dags/google_trends_dag.py took 0.049 seconds
[2023-07-27T09:31:19.654+0300] {processor.py:156} INFO - Started process (PID=262) to work on /opt/airflow/dags/google_trends_dag.py
[2023-07-27T09:31:19.655+0300] {processor.py:799} INFO - Processing file /opt/airflow/dags/google_trends_dag.py for tasks to queue
[2023-07-27T09:31:19.656+0300] {logging_mixin.py:149} INFO - [2023-07-27T09:31:19.656+0300] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/google_trends_dag.py
[2023-07-27T09:31:19.676+0300] {logging_mixin.py:149} INFO - [2023-07-27T09:31:19.674+0300] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/google_trends_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/google_trends_dag.py", line 74, in <module>
    dag_creator = GooogleTrendsMonthly()
  File "/opt/airflow/dags/google_trends_dag.py", line 41, in __init__
    self.dag:DAG = self.create_dag()
  File "/opt/airflow/dags/google_trends_dag.py", line 54, in create_dag
    update_monthly: PythonOperator = PythonOperator(
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/baseoperator.py", line 429, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/python.py", line 168, in __init__
    raise AirflowException("`python_callable` param must be callable")
airflow.exceptions.AirflowException: `python_callable` param must be callable
[2023-07-27T09:31:19.677+0300] {processor.py:811} WARNING - No viable dags retrieved from /opt/airflow/dags/google_trends_dag.py
[2023-07-27T09:31:19.699+0300] {processor.py:178} INFO - Processing /opt/airflow/dags/google_trends_dag.py took 0.050 seconds
[2023-07-27T09:31:49.840+0300] {processor.py:156} INFO - Started process (PID=271) to work on /opt/airflow/dags/google_trends_dag.py
[2023-07-27T09:31:49.842+0300] {processor.py:799} INFO - Processing file /opt/airflow/dags/google_trends_dag.py for tasks to queue
[2023-07-27T09:31:49.842+0300] {logging_mixin.py:149} INFO - [2023-07-27T09:31:49.842+0300] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/google_trends_dag.py
[2023-07-27T09:31:49.862+0300] {logging_mixin.py:149} INFO - [2023-07-27T09:31:49.860+0300] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/google_trends_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/google_trends_dag.py", line 74, in <module>
    dag_creator = GooogleTrendsMonthly()
  File "/opt/airflow/dags/google_trends_dag.py", line 41, in __init__
    self.dag:DAG = self.create_dag()
  File "/opt/airflow/dags/google_trends_dag.py", line 54, in create_dag
    update_monthly: PythonOperator = PythonOperator(
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/baseoperator.py", line 429, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/python.py", line 168, in __init__
    raise AirflowException("`python_callable` param must be callable")
airflow.exceptions.AirflowException: `python_callable` param must be callable
[2023-07-27T09:31:49.862+0300] {processor.py:811} WARNING - No viable dags retrieved from /opt/airflow/dags/google_trends_dag.py
[2023-07-27T09:31:49.892+0300] {processor.py:178} INFO - Processing /opt/airflow/dags/google_trends_dag.py took 0.055 seconds
[2023-07-27T09:32:19.999+0300] {processor.py:156} INFO - Started process (PID=279) to work on /opt/airflow/dags/google_trends_dag.py
[2023-07-27T09:32:20.001+0300] {processor.py:799} INFO - Processing file /opt/airflow/dags/google_trends_dag.py for tasks to queue
[2023-07-27T09:32:20.002+0300] {logging_mixin.py:149} INFO - [2023-07-27T09:32:20.002+0300] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/google_trends_dag.py
[2023-07-27T09:32:20.021+0300] {logging_mixin.py:149} INFO - [2023-07-27T09:32:20.018+0300] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/google_trends_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/google_trends_dag.py", line 74, in <module>
    dag_creator = GooogleTrendsMonthly()
  File "/opt/airflow/dags/google_trends_dag.py", line 41, in __init__
    self.dag:DAG = self.create_dag()
  File "/opt/airflow/dags/google_trends_dag.py", line 54, in create_dag
    update_monthly: PythonOperator = PythonOperator(
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/baseoperator.py", line 429, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/python.py", line 168, in __init__
    raise AirflowException("`python_callable` param must be callable")
airflow.exceptions.AirflowException: `python_callable` param must be callable
[2023-07-27T09:32:20.021+0300] {processor.py:811} WARNING - No viable dags retrieved from /opt/airflow/dags/google_trends_dag.py
[2023-07-27T09:32:20.048+0300] {processor.py:178} INFO - Processing /opt/airflow/dags/google_trends_dag.py took 0.054 seconds
[2023-07-27T09:32:50.181+0300] {processor.py:156} INFO - Started process (PID=287) to work on /opt/airflow/dags/google_trends_dag.py
[2023-07-27T09:32:50.184+0300] {processor.py:799} INFO - Processing file /opt/airflow/dags/google_trends_dag.py for tasks to queue
[2023-07-27T09:32:50.186+0300] {logging_mixin.py:149} INFO - [2023-07-27T09:32:50.185+0300] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/google_trends_dag.py
[2023-07-27T09:32:50.200+0300] {logging_mixin.py:149} INFO - [2023-07-27T09:32:50.198+0300] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/google_trends_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/google_trends_dag.py", line 74, in <module>
    dag_creator = GooogleTrendsMonthly()
  File "/opt/airflow/dags/google_trends_dag.py", line 41, in __init__
    self.dag:DAG = self.create_dag()
  File "/opt/airflow/dags/google_trends_dag.py", line 54, in create_dag
    update_monthly: PythonOperator = PythonOperator(
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/baseoperator.py", line 429, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/python.py", line 168, in __init__
    raise AirflowException("`python_callable` param must be callable")
airflow.exceptions.AirflowException: `python_callable` param must be callable
[2023-07-27T09:32:50.201+0300] {processor.py:811} WARNING - No viable dags retrieved from /opt/airflow/dags/google_trends_dag.py
[2023-07-27T09:32:50.223+0300] {processor.py:178} INFO - Processing /opt/airflow/dags/google_trends_dag.py took 0.046 seconds
[2023-07-27T09:33:20.355+0300] {processor.py:156} INFO - Started process (PID=295) to work on /opt/airflow/dags/google_trends_dag.py
[2023-07-27T09:33:20.357+0300] {processor.py:799} INFO - Processing file /opt/airflow/dags/google_trends_dag.py for tasks to queue
[2023-07-27T09:33:20.357+0300] {logging_mixin.py:149} INFO - [2023-07-27T09:33:20.357+0300] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/google_trends_dag.py
[2023-07-27T09:33:20.375+0300] {logging_mixin.py:149} INFO - [2023-07-27T09:33:20.373+0300] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/google_trends_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/google_trends_dag.py", line 74, in <module>
    dag_creator = GooogleTrendsMonthly()
  File "/opt/airflow/dags/google_trends_dag.py", line 41, in __init__
    self.dag:DAG = self.create_dag()
  File "/opt/airflow/dags/google_trends_dag.py", line 54, in create_dag
    update_monthly: PythonOperator = PythonOperator(
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/baseoperator.py", line 429, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/python.py", line 168, in __init__
    raise AirflowException("`python_callable` param must be callable")
airflow.exceptions.AirflowException: `python_callable` param must be callable
[2023-07-27T09:33:20.375+0300] {processor.py:811} WARNING - No viable dags retrieved from /opt/airflow/dags/google_trends_dag.py
[2023-07-27T09:33:20.401+0300] {processor.py:178} INFO - Processing /opt/airflow/dags/google_trends_dag.py took 0.050 seconds
[2023-07-27T12:39:59.387+0300] {processor.py:156} INFO - Started process (PID=26) to work on /opt/airflow/dags/google_trends_dag.py
[2023-07-27T12:39:59.389+0300] {processor.py:799} INFO - Processing file /opt/airflow/dags/google_trends_dag.py for tasks to queue
[2023-07-27T12:39:59.389+0300] {logging_mixin.py:149} INFO - [2023-07-27T12:39:59.389+0300] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/google_trends_dag.py
[2023-07-27T12:39:59.423+0300] {logging_mixin.py:149} INFO - [2023-07-27T12:39:59.420+0300] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/google_trends_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/google_trends_dag.py", line 74, in <module>
    dag_creator = GooogleTrendsMonthly()
  File "/opt/airflow/dags/google_trends_dag.py", line 41, in __init__
    self.dag:DAG = self.create_dag()
  File "/opt/airflow/dags/google_trends_dag.py", line 54, in create_dag
    update_monthly: PythonOperator = PythonOperator(
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/baseoperator.py", line 429, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/python.py", line 168, in __init__
    raise AirflowException("`python_callable` param must be callable")
airflow.exceptions.AirflowException: `python_callable` param must be callable
[2023-07-27T12:39:59.423+0300] {processor.py:811} WARNING - No viable dags retrieved from /opt/airflow/dags/google_trends_dag.py
[2023-07-27T12:39:59.458+0300] {processor.py:178} INFO - Processing /opt/airflow/dags/google_trends_dag.py took 0.077 seconds
[2023-07-27T12:40:29.617+0300] {processor.py:156} INFO - Started process (PID=34) to work on /opt/airflow/dags/google_trends_dag.py
[2023-07-27T12:40:29.618+0300] {processor.py:799} INFO - Processing file /opt/airflow/dags/google_trends_dag.py for tasks to queue
[2023-07-27T12:40:29.619+0300] {logging_mixin.py:149} INFO - [2023-07-27T12:40:29.619+0300] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/google_trends_dag.py
[2023-07-27T12:40:29.647+0300] {logging_mixin.py:149} INFO - [2023-07-27T12:40:29.645+0300] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/google_trends_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/google_trends_dag.py", line 74, in <module>
    dag_creator = GooogleTrendsMonthly()
  File "/opt/airflow/dags/google_trends_dag.py", line 41, in __init__
    self.dag:DAG = self.create_dag()
  File "/opt/airflow/dags/google_trends_dag.py", line 54, in create_dag
    update_monthly: PythonOperator = PythonOperator(
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/baseoperator.py", line 429, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/python.py", line 168, in __init__
    raise AirflowException("`python_callable` param must be callable")
airflow.exceptions.AirflowException: `python_callable` param must be callable
[2023-07-27T12:40:29.647+0300] {processor.py:811} WARNING - No viable dags retrieved from /opt/airflow/dags/google_trends_dag.py
[2023-07-27T12:40:29.683+0300] {processor.py:178} INFO - Processing /opt/airflow/dags/google_trends_dag.py took 0.071 seconds
[2023-07-27T12:40:59.801+0300] {processor.py:156} INFO - Started process (PID=42) to work on /opt/airflow/dags/google_trends_dag.py
[2023-07-27T12:40:59.802+0300] {processor.py:799} INFO - Processing file /opt/airflow/dags/google_trends_dag.py for tasks to queue
[2023-07-27T12:40:59.802+0300] {logging_mixin.py:149} INFO - [2023-07-27T12:40:59.802+0300] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/google_trends_dag.py
[2023-07-27T12:40:59.821+0300] {logging_mixin.py:149} INFO - [2023-07-27T12:40:59.819+0300] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/google_trends_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/google_trends_dag.py", line 74, in <module>
    dag_creator = GooogleTrendsMonthly()
  File "/opt/airflow/dags/google_trends_dag.py", line 41, in __init__
    self.dag:DAG = self.create_dag()
  File "/opt/airflow/dags/google_trends_dag.py", line 54, in create_dag
    update_monthly: PythonOperator = PythonOperator(
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/baseoperator.py", line 429, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/python.py", line 168, in __init__
    raise AirflowException("`python_callable` param must be callable")
airflow.exceptions.AirflowException: `python_callable` param must be callable
[2023-07-27T12:40:59.822+0300] {processor.py:811} WARNING - No viable dags retrieved from /opt/airflow/dags/google_trends_dag.py
[2023-07-27T12:40:59.854+0300] {processor.py:178} INFO - Processing /opt/airflow/dags/google_trends_dag.py took 0.057 seconds
